name: businessdesign
favicon: null
layout_spectrum: 0.61495
typography_spectrum: 0.8509290586225688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a29da2'
    - '#bf1d73'
    - '#e1e01c'
    - '#2684be'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
